export const dataConfig = [
  
    {   id:1,
        ProductName: "Chicken Breast Fillets",
        Brand: "Hormel Black",
        Price: "$60",
        Quantity: "0",
        Total: "0",
        Status: "", 
    },
    {    id:2,
          ProductName: "Chicken Breast Fillets",
          Brand: "Hormel Black",
          Price: "$60",
          Quantity: "2",
          Total: "0",
          Status: "", 
      },
      {  id:3,
         ProductName: "Chicken Breast Fillets",
          Brand: "Hormel Black",
          Price: "$60",
          Quantity: "5",
          Total: "0",
          Status: "", 
      },
      {  id:4,
         ProductName: "Chicken Breast Fillets",
          Brand: "Hormel Black",
          Price: "$60",
          Quantity: "10",
          Total: "0",
          Status: "", 
      },
      {   id:5,
          ProductName: "Chicken Breast Fillets",
          Brand: "Hormel Black",
          Price: "$60",
          Quantity: "2",
          Total: "0",
          Status: "", 
      },
      {   id:6,
          ProductName: "Chicken Breast Fillets",
          Brand: "Hormel Black",
          Price: "$60",
          Quantity: "12",
          Total: "0",
          Status: "", 
      },
  
 
];
